modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="atlas_multi"
version="0.0.7"
displayName="atlas multi superpack "
credits="model designer, textures - ROLEMAYMOLY, model animator and developer - declan234e"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="declan234e, ROLEMAYMOLY"
description='''
just adds reactors
'''

[[dependencies.atlas_multi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




