modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 2 (GPLv2)"

[[mods]]
modId="oblivion"
version="0.1.2G"
displayName="oblivion"
credits="model designer, textures - ROLEMAYMOLY, model animator and developer - declan234e"
displayURL="https://gamer234emp.ga/oblivion"
updateJSONURL="https://raw.githubusercontent.com/declan234e/gamer234emp.ga/master/oblivionUPDATE.json"
logoFile="logo.png"
authors="declan234e, ROLEMAYMOLY"
description='''
not alot
'''

[[dependencies.oblivion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




