modLoader="javafml"
loaderVersion="[37,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="oblivion"
version="0.1.1B"
displayName="oblivion"
credits="model designer, textures - ROLEMAYMOLY, model animator and developer - declan234e"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="declan234e, ROLEMAYMOLY"
description='''
not alot
'''

[[dependencies.oblivion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




